<?php
module_load_include('module','ws_client');
/**
 * Implements hook_block_info()
 */
function mes_sinistres_block_info() {
  return array(
    'mes_sinistres' => array(
      'info' => t('Sinistres client'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view()
 */
function mes_sinistres_block_view($delta = '') {
  if ($delta == 'mes_sinistres') {
    $title = '';
  	$output = '';



    $table_auto = array(
      'thead' => array(
        'date_survenance' => 'Date survenance',
        'numero_sinistre' => 'N° Sinistre',
        'evenements' => t('Evénements'),
        'status' => t('Status'),
      ),
      'tbody' => array(
        array(
          'date_survenance' => '10/07/2017',
          'numero_sinistre' => '2501457882',
          'evenements' => 'Bris de Glace',
          'status' => t('En cours'),    
        ),
        array(
          'date_survenance' => '10/07/2016',
          'numero_sinistre' => '2501478923',
          'evenements' => 'Collision entre vehicules',
          'status' => t('Terminé'),
        ),
      ),
    );

    $table_habitation = array(
      'thead' => array(
        'date_survenance' => 'Date survenance',
        'numero_sinistre' => 'N° Sinistre',
        'evenements' => t('Evénements'),
        'status' => t('Status'),
      ),
      'tbody' => array(
        array(
          'date_survenance' => '11/01/2015',
          'numero_sinistre' => '2500145780',
          'evenements' => 'Dégat des eaux',
          'status' => t('Terminé'),    
        ),
      ),
    );

    $get_service_sinistres = array(
      array(
        'type' => 'Auto',
        'id' => array(
                  'numero_contrat' => '251463987',
                  'info_sup' => 'Immatriculation LU2667',
                ),
        'tableau' => $table_auto,
      ),
      array(
        'type' => 'Habitation',
        'id' => array(
                  'numero_contrat' => '251463987',
                  'info_sup' => 'Adresse: Gueule tapée Rue 67*52',
                ),
        'tableau' => $table_habitation,
      ),

    );
    /*var_dump($get_service_sinistres)[0];*/
    //$get_service_sinistres = ws_client_get_liste_sinistres();
    /*var_dump($get_service_sinistres)[0]; die();*/

    $title_sinistre = t('Mes Sinistres');
    $title_span = t('Suivi de mes déclarations sinistres'); 
    
    $title .= '<p>'. $title_sinistre .'</p>';
    $title .= '<span>'. $title_span .'</span>';

    foreach ($get_service_sinistres as $sinistre) {
      # code...
      $output .= '<div class="item-type-sinistre">';
      $output .=   '<h3 class="title-sinistre">';
      $output .=     'Suivi de vos sinistres '. $sinistre['type'];
      $output .=   '</h3>';
      $output .=   '<div class="item-info-contrat">';
      $output .=      '<h3>';
      $output .=        'Contrat '. $sinistre['id']['numero_contrat'] . ' / '. $sinistre['id']['info_sup'];
      $output .=      '</h3>';
      $output .= '<table class="table table-bordered">';
      $output .=   '<thead>';
      foreach ($sinistre['tableau']['thead'] as $key => $value) {
        # code...
          $output .=     '<th>'. $value .'</th>';
      }
      $output .=   '</thead>';
      $output .=   '<tbody>';
      foreach ($sinistre['tableau']['tbody'] as $tables) {
        # code...
        $output .= '<tr>';
        foreach ($tables as $key => $value) {
          # code...
          $output .=   '<td>'. $value .'</td>';
        }
        $output .= '</tr>';
      }
      $output .=       '</tbody>';
      $output .=     '</table>';   
      $output .=   '</div>';
      $output .= '</div>';
    }
    
    return array(
      'subject' => $title,
      'content' => (!empty($output)) ? '<div class="sinistre_body">' . $output . '</div>' : '<p>' . t('For now, this list is empty!') . '</p>',
    );
  }

  return array();
}