<?php
/**
 * Implements hook_block_info()
 */
function rendez_vous_block_info() {
  return array(
    'rendez_vous' => array(
      'info' => t('Rendez-vous avec le conseiller'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view()
 */
function rendez_vous_block_view($delta = '') {
  $block = array();
  if ($delta == 'rendez_vous') {
    $nom_conseiller = "Aliou Samba WELE";
    $block['subject'] = '<p>'. 'Fixer un rendez vous avec mon conseiller' .'</p>';
    $block['subject'] .= '<span>'. $nom_conseiller . '</span>'; 
    $block['content'] = drupal_get_form('fixer_rendez_vous_form');
  }

  return $block;
}

/**
 * fixer_rendez_vous_form
 */
function fixer_rendez_vous_form($form, &$form_state){
  global $user;
  $user_load = user_load($user->uid);

  $form['objet'] = array(
    '#type' => 'select',
    '#title' => t('Objet du contrat'),
    '#options' => array(
      0 => t('Souscription d\'un nouveau contrat'),
      1 => t('Demande d\'information'),
      2 => t('Résiliation contrat'),
    ), 
    '#required' => TRUE,
  );
  $form['demande'] = array(
    '#title' => t('Demande'),
    '#type' => 'textarea',
    '#default_value' => t(''),
    '#required' => TRUE,
  );

  $form['moyen_contact'] = array(
    '#type' => 'select',
    '#title' => t('Je souhaite être contacter par'),
    '#options' => array(
      'SMS' => t('SMS'),
      'EMAIL' => t('Email'),
    ), 
    '#required' => TRUE,
  );

  $form['sms'] = array(
    '#type' => 'textfield',
    '#title' => t('Numéro de téléphone'),
    '#default_value' => '778241624',
    '#states' => array(
      'visible' => array(
        ':input[name="moyen_contact"]' => array('value' => 'SMS'),
      ),
    ),
  );

  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Adresse mail'),
    '#default_value' => $user_load->mail,
    '#states' => array(
      'visible' => array(
        ':input[name="moyen_contact"]' => array('value' => 'EMAIL'),
      ),
    ),
  );

  $form['date'] = array(
    '#type' => 'date', 
    '#title' => t('Dans la journée de'), 
    '#default_value' =>  array('year' => 2017, 'month' => 2, 'day' => 15), 
    '#required' => TRUE,
  );

  $form['horaire'] = array(
    '#type' => 'select',
    '#title' => t('Aux horaires suivants'),
    '#options' => array(
      0 => t('08h-13h'),
      1 => t('16h-18h'),
    ),
    '#required' => TRUE,
  );


  $form['submit'] = array(
    '#type' => 'submit', 
    '#title' => 'Enregistrer',
    '#values' => 'Enregistrer',
  );
  
  $form['#submit'][] = 'fixer_rendez_vous_form_submit';


  
  return system_settings_form($form);

}