<?php
module_load_include('module','ws_client');



/**
 * Implements hook_libraries_info().
 */
function rendez_vous_libraries_info() {
  $libraries['phpmailer'] = array(
    'name' => 'PHPMailer library',
    'vendor url' => 'http://www.phpmailer.com',
    'download url' => 'https://github.com/PHPMailer/PHPMailer',
    'path' => '.',
    'version' => '5.2.23',
    'files' => array(
      'php' => array(
        'PHPMailerautoload.php',
      ),
    ),
  );
  return $libraries;
}


/**
 * Implements hook_block_info()
 */
function rendez_vous_block_info() {
  return array(
    'rendez_vous' => array(
      'info' => t('Rendez-vous avec le conseiller'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view()
 */
function rendez_vous_block_view($delta = '') {
  
  //$get_service_conseiller = ws_client_get_info_conseiller();
  $get_service_conseiller = array(
    'nomComplet' => 'Aliou Samba Wele',
    'adresse' => 'Gueule Tapée',
    'mail' => 'smsframework@gmail.com',
    'telephone' => '778088470',
  );

  $block = array();
  if ($delta == 'rendez_vous') {
    $nom_conseiller = $get_service_conseiller['nomComplet'];
    $block['subject'] = '<p>'. 'Fixer un rendez vous avec mon conseiller' .'</p>';
    $block['subject'] .= '<span>'. $nom_conseiller . '</span>'; 
    $block['content'] = drupal_get_form('fixer_rendez_vous_form');
  }

  return $block;
}

/**
 * fixer_rendez_vous_form
 */
function fixer_rendez_vous_form($form, &$form_state){
  global $user;
  $user_load = user_load($user->uid);

  $form['objet'] = array(
    '#type' => 'select',
    '#title' => t('Objet du contrat'),
    '#options' => array(
      0 => t('Souscription d\'un nouveau contrat'),
      1 => t('Demande d\'information'),
      2 => t('Résiliation contrat'),
    ), 
    '#required' => TRUE,
  );
  $form['demande'] = array(
    '#title' => t('Demande'),
    '#type' => 'textarea',
    '#default_value' => t(''),
    '#required' => TRUE,
  );

  $form['moyen_contact'] = array(
    '#type' => 'select',
    '#title' => t('Je souhaite être contacter par'),
    '#options' => array(
      'SMS' => t('SMS'),
      'EMAIL' => t('Email'),
    ), 
    '#required' => TRUE,
  );

  $form['sms'] = array(
    '#type' => 'textfield',
    '#title' => t('Numéro de téléphone'),
    '#default_value' => '778241624',
    '#states' => array(
      'visible' => array(
        ':input[name="moyen_contact"]' => array('value' => 'SMS'),
      ),
    ),
  );

  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Adresse mail'),
    '#default_value' => $user_load->mail,
    '#states' => array(
      'visible' => array(
        ':input[name="moyen_contact"]' => array('value' => 'EMAIL'),
      ),
    ),
  );

  $form['date'] = array(
    '#type' => 'date', 
    '#title' => t('Dans la journée de'), 
    '#default_value' =>  array('year' => 2017, 'month' => 2, 'day' => 15), 
    '#required' => TRUE,
  );

  $form['horaire'] = array(
    '#type' => 'select',
    '#title' => t('Aux horaires suivants'),
    '#options' => array(
      0 => t('08h-13h'),
      1 => t('16h-18h'),
    ),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit', 
    '#title' => 'Enregistrer',
    '#value' => 'Fixer un RDV',
    '#submit' => array('rendez_vous_form_submit'),
  );
    
  return system_settings_form($form);

}


function rendez_vous_form_submit($form, &$form_state){
    global $user;
    $account = user_load_by_name($user->name);

    //$get_service_conseiller = ws_client_get_info_conseiller();
    $get_service_conseiller = array(
      'nomComplet' => 'Aliou Samba Wele',
      'adresse' => 'Gueule Tapée',
      'mail' => 'smsframework@gmail.com',
      'telephone' => '778088470',
    );
    

    $horaire = array(
      0 => t('08h-13h'),
      1 => t('15h-18h'),
    );

    $option = array(
      0 => t('Souscription d\'un nouveau contrat'),
      1 => t('Demande d\'information'),
      2 => t('Résiliation contrat'),
    );

    $demande = $form_state['values']['demande'];
    $option_value = $option[$form_state['values']['objet']];
    $horaire_value = $horaire[$form_state['values']['horaire']]; 

    $to = $get_service_conseiller['mail'];
    $from = "mouhawele@gmail.com";
    $subject = $option_value;
    $body = $form_state['values']['demande'] . ' ' .$horaire_value;
    $alt = 'Fixer un rendez vous';

    envoyer_mail($from, $to, $subject, $body, $alt);
}

function envoyer_mail($from, $to, $subject, $body, $alt){
  $host = variable_get('cron_notification_mail_smtp');
  $smtp_secure = variable_get('cron_notification_mail_smtpsecure');
  $port = (int) variable_get('cron_notification_mail_port');
  $username = variable_get('cron_notification_mail_username');
  $password = variable_get('cron_notification_mail_password');

  $mail = new PHPMailer;
  $mail->SMTPDebug = 3;                               // Enable verbose debug output
  $mail->isSMTP();                                      // Set mailer to use SMTP
  $mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
  $mail->SMTPAuth = true;                               // Enable SMTP authentication


  $mail->Username = $username;                 // SMTP username
  $mail->Password = $password;                           // SMTP password
  $mail->SMTPSecure = $smtp_secure;                            // Enable TLS encryption, `ssl` also accepted
  $mail->Port = $port;                                    // TCP port to connect to

  $mail->setFrom($from, $alt);
  $mail->addAddress($to);     // Add a recipient
  
  $mail->isHTML(true);                                  // Set email format to HTML

  $mail->Subject = $subject;
  $mail->Body    = $body;

  if(!$mail->send()) {
      echo 'Message could not be sent.';
      echo 'Mailer Error: ' . $mail->ErrorInfo;
  }  else {
      echo 'Message has been sent';
  }
}