<?php
require_once DRUPAL_ROOT . '/' . variable_get('password_inc', 'includes/password.inc');
module_load_include('module','ws_client');

/**
 * Implements hook_block_info()
 */
function form_information_block_info() {
  return array(
    'form_information' => array(
      'info' => t('Information du client'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view()
 */
function form_information_block_view($delta = '') {
  $block = array();
  if ($delta == 'form_information') {
    $block['subject'] = '<p>'. 'Mes informations personnelles' .'</p>'; 
    $block['content'] = drupal_get_form('form_information_form');
  }

  return $block;
}

/**
 * form_informaton form
 */
function form_information_form($form, &$form_state){
  global $user;
/*  var_dump($user->roles); die();*/

  $infoPerso = ws_client_getInfoUser();

      $form['titre'] = array(
      '#type' => 'fieldset', 
      '#title' => t('Mes Informations Personnelles'), 
      );
      
      $form['nom'] = array(
        '#type' => 'textfield', 
        '#title' => 'Nom',
        '#default_value' => $infoPerso['nom'],
        '#required' => TRUE,
      );

      $form['prenom'] = array(
        '#type' => 'textfield', 
        '#title' => 'Prénom',
        '#default_value' => $infoPerso['prenom'],
        '#required' => TRUE,
      );

      $form['adresse'] = array(
        '#type' => 'textfield', 
        '#title' => 'Adresse',
        '#default_value' => $infoPerso['adresse'],
        '#required' => TRUE,
      );

      $form['email'] = array(
        '#type' => 'textfield', 
        '#title' => 'Email',
        '#default_value' => $infoPerso['mail'],
        '#required' => TRUE,
      );

      $form['telephone'] = array(
        '#type' => 'textfield', 
        '#title' => 'Téléphone',
        '#default_value' => $infoPerso['telephone'],
        '#required' => TRUE,
      );

      $form['change_pass'] = array(
        '#type' => 'checkbox',
        '#title' => t('Changer de code confidentiel'),
      );

      $form['pass'] = array(
        '#title' => t('Code confidentiel'),
        '#type' => 'fieldset',
        '#states' => array(
          'visible' => array(
            ':input[name="change_pass"]' => array('checked' => TRUE),
          ),
        ),
      );

      $form['pass']['pass'] = array(
        '#type' => 'password', 
        '#title' => 'Ancien code confidentiel', 
        '#maxlength' => 64, 
        '#size' => 15,
        '#required' => FALSE,
      );

      $form['pass']['pass1'] = array(
        '#type' => 'password', 
        '#title' => 'Nouveau code confidentiel', 
        '#maxlength' => 64, 
        '#size' => 15,
        '#required' => FALSE,
      );

      $form['pass']['pass2'] = array(
        '#type' => 'password', 
        '#title' => t('Confirme code confidentiel'), 
        '#maxlength' => 64, 
        '#size' => 15,
        '#required' => FALSE,
      );

      $form['submit'] = array(
        '#type' => 'submit', 
        '#title' => 'Enregistrer',
      );

      $form['#submit'][] = 'form_information_form_submit';


  return system_settings_form($form);

}

/**
 *Validation handler
 */
function form_information_form_validate($form, &$form_state) {
  /*print('<pre>'. print_r($form_state['values'], TRUE) .'</pre>'); die();*/
  global $user;
  $account = user_load_by_name($user->name);

  if($form_state['values']['change_pass']){
    
    if(!user_check_password($form_state['values']['pass'], $account)){
      form_set_error('pass', t('User error: ancien code cofidentiel invalide'));
      return FALSE;
    }

    if(!is_numeric($form_state['values']['pass'])){
      form_set_error('pass', t('User error: entrer un code cofidentiel valide'));
      return FALSE;
    }

    if(!is_numeric($form_state['values']['pass1'])){
      form_set_error('pass1', t('User error: entrer un code cofidentiel valide'));
      return FALSE;
    }

    if(!is_numeric($form_state['values']['pass2'])){
      form_set_error('pass2', t('User error: entrer un code cofidentiel valide'));
      return FALSE;
    }

    if(!($form_state['values']['pass1'] === $form_state['values']['pass2'])){
      form_set_error('pass', t('User error: code confidentiel non conforme'));
      return FALSE;
    }
  }


  if(!is_numeric($form_state['values']['telephone'])){
    form_set_error('telephone', t('User error: enter a valide number'));
    return FALSE;
  }


  return TRUE;
}


function form_information_form_submit($form, &$form_state){
    global $user;
    $edit = array();
    $update = array();
    $account = user_load_by_name($user->name);

    if (isset($form_state['values']['pass1'])){
      $edit['pass'] = $form_state['values']['pass1'];     
      user_save($account, $edit);
    }

    $update['nom'] = $form_state['values']['nom'];
    $update['prenom'] = $form_state['values']['prenom'];
    $update['adresse'] = $form_state['values']['adresse'];
    $update['mail'] = $form_state['values']['email'];
    $update['telephone'] = $form_state['values']['telephone'];

    ws_client_update_info_user($update);
}