<?php
module_load_include('module','ws_client');
/**
 * Implements hook_block_info()
 */
function mes_devis_block_info() {
  return array(
    'mes_devis' => array(
      'info' => t('devis client'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view()
 */
function mes_devis_block_view($delta = '') {
  if ($delta == 'mes_devis') {
    $title = '';
  	$output = '';

    $get_service_devis = ws_client_get_liste_devis();


    $get_service_devis = isset($get_service_devis) ? $get_service_devis : $get_test_devis;

    $title .=   t('Mes devis');

    $output .= '<div class="item-mes-devis">';
    foreach ($get_service_devis as $devis) {
      # code...
      $output .=   '<h3>';
      $output .=     $devis['type'];
      $output .=   '</h3>';
      $output .=   '<div class="row item-devis">';
      foreach ($devis['tableau'] as $tableau) {
      	# code...
      	foreach ($tableau as $value) {
      		# code...
      		$output .= '<div class="field-devis col-lg-6">';
      		$output .= '<span>'. $value . '</span>';
      		$output .= '</div>';
      	}
      }

      $output .=   '</div>';
    }
    $output .= '</div>';

    return array(
      'subject' => $title ,
      'content' => (!empty($output)) ? '<div class="devis_body">' . $output . '</div>' : '<p>' . t('For now, this list is empty!') . '</p>',
    );
  }

  return array();
}