<?php
module_load_include('module','ws_client');
/**
 * Implements hook_block_info()
 */
function mes_devis_block_info() {
  return array(
    'mes_devis' => array(
      'info' => t('devis client'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view()
 */
function mes_devis_block_view($delta = '') {
  if ($delta == 'mes_devis') {
    $title = '';
  	$output = '';
    $get_service_devis = ws_client_get_liste_devis();
    //var_dump($get_service_devis); die();
    $tmp = $get_service_devis;
    $i=0;
    foreach ($tmp as $devis) {
      # code...
      foreach ($devis['tableau'] as $key_value) {
        # code...
        $tmp[$i]['tab'][$key_value[0]] = $key_value[1];  
      }
      unset($tmp[$i]['tableau']);
      $i = $i + 1;  
    }

    foreach ($tmp as $tab) {
      # code...
      $array_tmp[$tab['type']][] = $tab['tab']; 
    }
    
    $i = 0;
    foreach ($array_tmp as $key_tmp => $value_tmp) {
      # code...
      $array[$i]['type'] = $key_tmp;
      $array[$i]['info'] = $value_tmp;
      $i++;
    }
    //var_dump($array[0]['info']);var_dump($array[1]['info']); die();
    //$get_service_devis = isset($get_service_devis) ? $get_service_devis : $get_test_devis;

    $title .=   t('Mes devis');

    $output .= '<div class="item-mes-devis">';
    foreach ($array as $devis) {
      # code...
        if(isset($devis['type']))
        {
          $output .=   '<h3>';
          $output .=     $devis['type'];
          $output .=   '</h3>';
          $output .=   '<div class="row item-devis">';

          $output .= '<div class="titleProduit col-lg-12">
                          <div class="col-lg-3"><span>Numéro</span></div> ';
          if($devis['type'] === 'Type Auto'){
              $output  .='<div class="col-lg-4"><span>Marque</span></div>
                          <div class="col-lg-3"><span>Modéle</span></div>';
          }
          if($devis['type'] === 'Type habitation'){
              $output  .='<div class="col-lg-4"><span>Type de logement</span></div>
                          <div class="col-lg-3"><span>Adresse</span></div>';
          }
          if($devis['type'] === 'Assistance & Accidents' || $devis['type'] === 'Type Loisirs-Vie privée'){
              $output  .='<div class="col-lg-4"><span>Type de contrat</span></div>
                          <div class="col-lg-3"><span>A complété</span></div>';
          }
           $output  .= ' <div class="col-lg-2"><span>Action</span></div>
                        </div>' ;
                        
          foreach ($devis['info'] as $informations) {
            # code...
            $i = 0;
            //$numdevis = $informations['id'];
            foreach ($informations as $key => $value) {
              # code...
              if($i==0){
                $output .=     '<div class="col-lg-4 field-devis">';
                $output .=       '<span><a href="#">'. $value .'</a></span>';      
                $output .=     '</div>';    
              }
              elseif($i==1){
                $output .=     '<div class="col-lg-4 field-devis">';
                $output .=       '<span>'. $value .'</span>';      
                $output .=     '</div>'; 
              }
              else{
                $output .=     '<div class="col-lg-4 field-devis">';
                $output .=       '<span>'. $value .'</span>';      
                $output .=     '</div>';
              }
              $i++;

            }      
          }
          $output .=   '</div>';
      }    
    }
    $output .= '</div>';

    /*$output .= '<div class="item-mes-devis">';
    foreach ($get_service_devis as $devis) {
      # code...
      $output .=   '<h3>';
      $output .=     $devis['type'];
      $output .=   '</h3>';
      $output .=   '<div class="row item-devis">';
      foreach ($devis['tableau'] as $tableau) {
      	# code...
      	foreach ($tableau as $value) {
      		# code...
      		$output .= '<div class="field-devis col-lg-6">';
      		$output .= '<span>'. $value . '</span>';
      		$output .= '</div>';
      	}
      }

      $output .=   '</div>';
    }
    $output .= '</div>';*/

    return array(
      'subject' => $title ,
      'content' => (!empty($output)) ? '<div class="devis_body">' . $output . '</div>' : '<p>' . t('For now, this list is empty!') . '</p>',
    );
  }

  return array();
}