<?php
module_load_include('module','ws_client');
/**
 * Implements hook_block_info()
 */
function mes_devis_block_info() {
  return array(
    'mes_devis' => array(
      'info' => t('devis client'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view()
 */
function mes_devis_block_view($delta = '') {
  if ($delta == 'mes_devis') {
    $title = '';
  	$output = '';
    $tmp = ws_client_get_liste_devis();
    $i=0;
    /*foreach ($tmp as $devis) {*/
/*      foreach ($devis['tableau'] as $key_value) {
        $tmp[$i]['tab'][$key_value[0]] = $key_value[1];  
      }
      unset($tmp[$i]['tableau']);
      $i = $i + 1;  
    }

    foreach ($tmp as $tab) {
      # code...
      $array_tmp[$tab['type']][] = $tab['tab']; 
    }
    
    $i = 0;
    foreach ($array_tmp as $key_tmp => $value_tmp) {
      # code...
      $array[$i]['type'] = $key_tmp;
      $array[$i]['info'] = $value_tmp;
      $i++;
    }*/
    //var_dump($array[0]['info']);var_dump($array[1]['info']); die();
    //$get_service_devis = isset($get_service_devis) ? $get_service_devis : $get_test_devis;

    $title .=   t('Mes devis');

    $output .= '<div class="item-mes-devis">';
    foreach ($tmp as $devis) {
      # code...
        if(isset($devis['type']))
        {
          $output .=   '<h3>';
          $output .=     $devis['type'];
          $output .=   '</h3>';
          $output .=   '<div class="row item-devis">';
          foreach ($devis['info'] as $informations) {
            # code...
            $i = 0;
            $numdevis = $informations['id'];
            foreach ($informations as $key => $value) {
              # code...
              if($i==0){
                $output .= '<div class="col-lg-12">';  
                $output .=     '<div class="col-lg-3 field-devis">';
                $output .=     '<span>'.l($value,'devis/'.$numdevis).'</span>';
                /*$output .=       '<span><a href="#">'. $numdevis .'</a></span>';      */
                $output .=     '</div>';    
              }
              elseif($i==1){
                $output .=     '<div class="col-lg-4 field-devis">';
                $output .=       '<span>'. $value .'</span>';      
                $output .=     '</div>'; 
              }
              else{
                $output .=     '<div class="col-lg-3 field-devis">';
                $output .=       '<span>'. $value .'</span>';      
                $output .=     '</div>';
              }
              $i++;

            }
            $idownload ='<i class="fa fa-download" aria-hidden="true"></i>' ;
            $iview = '<i class="fa fa-eye" aria-hidden="true"></i>' ;
            $irequete ='<i class="fa fa-pencil-square-o" aria-hidden="true"></i>' ;
            $output .=     '<div class="col-lg-1 telechargement-devis field-devis">';
            $output .=       '<span> '.l($idownload ,'devis/'.$numdevis,array('html'=> true ,'attributes'=> array('target' => '_blank'))).'</span>';   
            $output .=     '</div>';
            $output .=     '<div class="col-lg-1 visualisation-devis field-devis">';
            $output .=       '<span> '.l($iview ,'devis/'.$numdevis,array('html'=> true)).'</span>';  
            $output .=     '</div>';
            $output .=     '</div>';
          }
          $output .=   '</div>';
      }    
    }
    $output .= '</div>';

    /*$output .= '<div class="item-mes-devis">';
    foreach ($get_service_devis as $devis) {
      # code...
      $output .=   '<h3>';
      $output .=     $devis['type'];
      $output .=   '</h3>';
      $output .=   '<div class="row item-devis">';
      foreach ($devis['tableau'] as $tableau) {
      	# code...
      	foreach ($tableau as $value) {
      		# code...
      		$output .= '<div class="field-devis col-lg-6">';
      		$output .= '<span>'. $value . '</span>';
      		$output .= '</div>';
      	}
      }

      $output .=   '</div>';
    }
    $output .= '</div>';*/

    return array(
      'subject' => $title ,
      'content' => (!empty($output)) ? '<div class="devis_body">' . $output . '</div>' : '<p>' . t('For now, this list is empty!') . '</p>',
    );
  /*}*/
}
  return array();
}

function mes_devis_menu() {
  $items['devis/%'] = array(
    'page callback' => 'detail_devis',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
    return $items;
}

function detail_devis($arg) {
  global $user ;
  $devis =  ws_client_get_devis_by_num($arg);
  //var_dump($devis) ; die();
  $nom = variable_get('nom_'.$user->uid);
  $prenom = variable_get('prenom_'.$user->uid);
  $dateNaissance = variable_get('dateNaissance_'.$user->uid);
  $civilite = variable_get('civilite_'.$user->uid);
  $adresse = variable_get('adresse_'.$user->uid);
  $tel = variable_get('telephone_'.$user->uid);
  $email= variable_get('mail_'.$user->uid);
  $carburant = array(
    100000001 => 'Gasoil',
    100000000 => 'Essence'
  );
   $boolean = array(
    true => 'Oui',
    false => 'Non'
  );
    $logement = array(
    100000000 => 'Appartement',
    100000001 => 'Maison',
    100000002 => 'Autres'
  );
    $accident_tab = array(
    100000000 => 'Voyage',
    100000001 => 'Evacuation Sanitaire',
    100000002 => 'Individuels accidents particulier',
  );
    $loisir_tab = array(
    100000000 => 'Plaisance',
    100000001 => 'RC chasse',
    100000002 => 'RC chevaux de selle',
    100000003 => 'RC chef de famille',
  );
$output  = "<div class='logo' width='323px' height='57px'> </div>
                 <div class='title'>
                    <h2>DEVIS D'ASSURANCE <span>" .$devis['typeContrat']. "<span></h2>
                 </div>
                 <div class='numContrat'>
                    <table>
                      <tr>
                      <td>Numero devis : </td>
                      <td>".$arg."</td>
                    </tr>
                    </table>
                 </div>
                 <div class='infoContrat'>
                  <table border='1'>
                    <tr>
                      <th colspan='2'>Informations Personelles</th>
                    </tr>
                    <tr>
                      <td>Nom</td>
                      <td>".$nom."</td>
                    </tr>
                    <tr>
                      <td>Prenom</td>
                      <td>".$prenom."</td>
                    </tr>
                    <tr>
                      <td>Email</td>
                      <td>".$email."</td>
                    </tr>
                    <tr>
                      <td>Téléphone</td>
                      <td>".$tel."</td>
                    </tr>
                    <tr>
                      <td>Adresse</td>
                      <td>".$adresse."</td>
                    </tr>
                    <tr>
                      <th colspan='2'>".$devis['typeContrat']."</th>
                    </tr>";
    if($devis['typeContrat'] === "Automobile") {
        $output .= "<tr>
                      <td>Type de bien</td>
                      <td>".$devis['marque']."</td>
                    </tr>
                    <tr>
                      <td>Modéle</td>
                      <td>".$devis['modele']."</td>
                    </tr>
                    <tr>
                      <td>Carosserie</td>
                      <td>".$devis['carosserie']."</td>
                    </tr>
                    <tr>
                      <td>Energie</td>
                      <td>".$carburant[$devis['carburant']]."</td>
                    </tr>
                    <tr>
                      <td>Puissance</td>
                      <td>".$devis['puissance']."</td>
                    </tr>
                    <tr>
                      <td>Date de 1ére mise en circulation</td>
                      <td>".$devis['dateMiseEnCirculation']."</td>
                    </tr>
                    <tr>
                      <td>Valeur à neuf</td>
                      <td>".$devis['valeurAneuf']."</td>
                    </tr>
                    ";
    }
    if($devis['typeContrat'] === "Habitation") {
        $output .= "
                    <tr>
                      <td>Type</td>
                      <td>".$logement[$devis['typeLogement']]."</td>
                    </tr>
                    <tr>
                      <td>Nombre de pièces</td>
                      <td>".$devis['nbPieces']."</td>
                    </tr>
                    <tr>
                      <td>Adresse</td>
                      <td>".$devis['adresseLogement']."</td>
                    </tr>
                    <tr>
                      <td>Montant</td>
                      <td>".$devis['montant']."</td>
                    </tr>
                    <tr>
                      <td>Etes-vous locataire</td>
                      <td>".$boolean[$devis['locataire']]."</td>
                    </tr>
                    <tr>
                      <td>Est-il votre résidence principale</td>
                      <td>".$boolean[$devis['locataire']]."</td>
                    </tr>
                  ";
    }
    if($devis['typeContrat'] === "Assistances & Accidents") {
        $output .= "<tr>
                      <td>Type d'assurance</td>
                      <td>".$accident_tab[$devis['typeAssurance']]."</td>
                    </tr>
                  ";
    }
    if($devis['typeContrat'] === "Loisirs-Vie privée") {
        $output .= "<tr>
                      <td>Type d'assurance</td>
                      <td>".$loisir_tab[$devis['typeAssurance']]."</td>
                    </tr>
                  ";
    }
     $output .= "</table>
                </div>" ;

  pdf_using_mpdf_api($output,"Devis ".$devis['typeContrat']);
/*  $pdf=new FPDF();
  $pdf->AddPage();
  $pdf->SetFont('Arial','B',16);
  $pdf->Cell(40,10,$html);
  $pdf->Output();*/

}