<?php
/**
 * Implements hook_block_info()
 */
function mon_conseiller_block_info() {
  return array(
    'mon_conseiller' => array(
      'info' => t('conseiller du client'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view()
 */
function mon_conseiller_block_view($delta = '') {
  if ($delta == 'mon_conseiller') {
    $title = '';
  	$output = '';

    $get_service_conseiller = array(
      'nom' => 'Aliou Samba WELE',
      'adresse' => 'Rue 67*52',
      'telephone' => '+221778088471',
      'email' => 'aliou-samba.wele@atos.net',
    );

    $title .=   t('Mon Conseiller');

    $output .= '<div class="conseiller-left-bar">';
    $output .= '<h3>Mon conseiller</h3>';
    foreach ($get_service_conseiller as $key => $value) {
      # code...
      $output .= '<p>'. $value . '</p>';
    }
    $output .= '<p><a href="#">Fixer un RDV </a></p>'; 
    $output .= '</div>';
    $output .= '<div class="blanc">';
    $output .= '</div>';
    $output .= '<div class="bas">';
    $output .= '</div>';
    $output .= '<div class="incline">';
    $output .= '</div>';

    return array(
      'subject' => '' ,
      'content' => (!empty($output)) ?   $output : '<p>' . t('For now, this list is empty!') . '</p>',
    );
  }

  return array();
}