<?php

/**
 * Implements hook_block_info()
 */
function mon_conseiller_block_info() {
  return array(
    'mon_conseiller' => array(
      'info' => t('conseiller du client'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view()
 */
function mon_conseiller_block_view($delta = '') {
  if ($delta == 'mon_conseiller') {
    $title = '';
  	$output = '';

    //$get_service_conseiller = ws_client_get_info_conseiller();

    $title .=   t('Mon Conseiller');

    $output .= '<div class="conseiller-left-bar">';
    $output .= '<h3>Mon conseiller</h3>';
    /*foreach ($get_service_conseiller as $key => $value) {
      # code...
      $output .= '<p>'. $value . '</p>';
    }*/
    $output .= '<p><a href="?q=node/2&qt-left_menu=7">Fixer un RDV </a></p>'; 
    $output .= '</div>';
    $output .= '<div class="blanc">';
    $output .= '</div>';
    $output .= '<div class="bas">';
    $output .= '</div>';
    $output .= '<div class="incline">';
    $output .= '</div>';

    return array(
      'subject' => '' ,
      'content' => (!empty($output)) ?   $output : '<p>' . t('For now, this list is empty!') . '</p>',
    );
  }

  return array();
}