<?php
module_load_include('module','ws_client');
/**
 * Implements hook_block_info()
 */
function mes_contrats_block_info() {
  return array(
    'mes_contrats' => array(
      'info' => t('Contrats client'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view()
 */
function mes_contrats_block_view($delta = '') {
  if ($delta == 'mes_contrats') {
    $title = '';
  	$output = '';
    /*$auto = array();

    $auto['type'] = 'Auto';
    $auto['info'][] = array(
      'id' => '1234',
      'marque' => 'logeme',
      'modele' => 'assurance',  
    );
    $auto['info'][] = array(
      'id' => 'id',
      'marque' => 'marque',
      'modele' => 'modele',  
    );

    var_dump($auto); die();*/


    $get_service_contrats = ws_client_get_liste_contrats();


    /*var_dump($get_test_contrats); var_dump($get_service_contrats) ; die();*/

    $get_service_contrats = isset($get_service_contrats) ? $get_service_contrats : $get_test_contrats;

    $title .=   t('Mes Contrats');

    $output .= '<div class="item-mes-contrats">';
    foreach ($get_service_contrats as $contrat) {
      # code...
        if(isset($contrat['type']))
        {
          $output .=   '<h3>';
          $output .=     'Assurance '. $contrat['type'];
          $output .=   '</h3>';
          $output .=   '<div class="row item-contrat">';
          foreach ($contrat['info'] as $informations) {
            # code...
            $i = 0;
            foreach ($informations as $key => $value) {
              # code...
              if($i==0){
                $output .=     '<div class="col-lg-3 field-contrat">';
                $output .=       '<span><a href="#">'. $value .'</a></span>';      
                $output .=     '</div>';    
              }
              elseif($i==1){
                $output .=     '<div class="col-lg-4 field-contrat">';
                $output .=       '<span>'. $value .'</span>';      
                $output .=     '</div>'; 
              }
              else{
                $output .=     '<div class="col-lg-2 field-contrat">';
                $output .=       '<span>'. $value .'</span>';      
                $output .=     '</div>';
              }
              $i++;
            }
            $output .=     '<div class="col-lg-1 telechargement-contrat field-contrat">';
            $output .=       '<a href="#"><i class="fa fa-download" aria-hidden="true"></i></a>';      
            $output .=     '</div>';
            $output .=     '<div class="col-lg-1 visualisation-contrat field-contrat">';
            $output .=       '<a href="contrat-pdf.php"><i class="fa fa-eye" aria-hidden="true"></i></a>';      
            $output .=     '</div>';
            $output .=     '<div class="col-lg-1 requete-contrat field-contrat">';
            $output .=       '<a href="#"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>';      
            $output .=     '</div>';
          }
          $output .=   '</div>';
      }    
    }
    $output .= '</div>';

    return array(
      'subject' => $title ,
      'content' => (!empty($output)) ? '<div class="contrat_body">' . $output . '</div>' : '<p>' . t('For now, this list is empty!') . '</p>',
    );
  }

  return array();
}