<?php



/**
 * @file
 * ws_client module
 */

/**
 * Define constants for ws_client
 */
define('WS_CLIENT_ADMIN_PATH', 'admin/config/system/ws_client');



/**
 * Load module include files.
 */
module_load_include('inc', 'ws_client', 'ws_client.admin');

/**
 * Implements hook_permission()
 */
function ws_client_permission() {
  return array(
    'administer  ws_client' => array(
    'title' => t('administer ws client'),
    'description' => t('Perform administration end point ws client.'),
    ),
  );
}

/**
 * Implements hook_menu()
 */
function ws_client_menu() {
  $items[WS_CLIENT_ADMIN_PATH] = array(
    'title' => 'WS Client Settings',
    'description' => 'Administer your ws clien',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ws_client_admin_form'),
    'access arguments' => array('administer ws_client'),
    'file' => 'ws_client.admin.inc',
  );

  return $items;
}

	/**
	* @file
	* Web services Client
	*/
function  ws_client_block_info() {
	$blocks['ws_client_block_info'] = array('info' => t('web service client'));
	return $blocks ;
}
function  ws_client_block_view($delta = '') {
	$block['content'] = '<h1>Web Services client</h1>';
	$get_node_result = ws_client_getClient_node();
	/*krumong('main')->kPrint($get_node_result);*/	
	$data = json_decode($get_node_result->data);
	/*krumong('main')->kPrint($data);*/
	return $block ;
}

function ws_client_get_node(){
	$url = "http://192.168.43.145/ServicesCompte.svc/compte/espaceClient/AXA00000004/" ;
  $options = array('timeout' => 6000.0) ;
	return drupal_http_request($url , $options) ;
}


function ws_client_getIdClient($numeroContrat){

	//$url = "http://192.168.200.16/Service1.svc/compte/espaceClient/id/". $numeroContrat ."";

  $ip = variable_get('ip_server');
  $root = variable_get('root');
  $id_client = variable_get('retrieve_client_id');

  $url = 'http://'. $ip .'/'. $root .'/' . $id_client .'/'. $numeroContrat;

  $options = array('timeout' => 6000.0) ;
	$request = drupal_http_request($url ,$options) ;

  return drupal_json_decode($request->data);
}
/*
function ws_client_getInfoUser(){
  // URL Webservice
  $ip = variable_get('ip_server');
  $root = variable_get('root');
  $info_user = variable_get('retrieve_info_user');

  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;
  //$url = "http://192.168.200.16/Service1.svc/compte/espaceClient/infos/" .$identifiant. "";

  $url = 'http://'. $ip .'/'. $root .'/' . $info_user .'/'. $identifiant;
  $options = array('timeout' => 500.0) ;
  $request = drupal_http_request($url ,$options) ;
  //var_dump($request) ; die();
  $data = drupal_json_decode($request->data) ;
/*  if(!empty($data))
  {
    $returnArray = array(
      'nom' => $data['nom'] ,
      'prenom' => $data['prenom'] ,
      'adresse' => $data['adresse'] ,
      'telephone' => $data['telephone'] ,
      'mail' => $data['mail'], 
    );
   //var_dump($returnArray) ; die();
    return $returnArray ;
  /*}

  //var_dump($returnArray) ; die(); 
  
}*/

function ws_client_get_liste_sinistres(){
  // URL Webservice
  $ip = variable_get('ip_server');
  $root = variable_get('root');
  $liste_sinistres = variable_get('retrieve_liste_sinistres');

  $returnArray = array();
  
  $status = array(
    100000000 => 'Nouveau',
    100000001 => 'En cours',
    100000002 => 'Terminé',
  );

  $evenement_habitation = array(
    100000000 => 'Incendie',
    100000001 => 'Vol',
    100000002 => 'Cambriolage',
    100000003 => 'Degâts des eaux',
    100000004 => 'Vent violent',
  );

  $evenement_auto = array(
    100000000 => 'Accident',
    100000001 => 'Bris de glace',
    100000002 => 'Incendie',
    100000003 => 'Vol',
    100000004 => 'Cambriolage',
  );

  $evenement_accident = array(
    100000000 => 'Accident',
    100000001 => 'Bris de glace',
    100000002 => 'Incendie',
    100000003 => 'Vol',
    100000004 => 'Cambriolage',
  );
  
  $evenement_loisir = array(
    100000000 => 'Accident',
    100000001 => 'Bris de glace',
    100000002 => 'Incendie',
    100000003 => 'Vol',
    100000004 => 'Cambriolage',
  );


  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;

  $url = 'http://'. $ip .'/'. $root .'/' . $liste_sinistres .'/'. $identifiant;
  
  $options = array('timeout' => 6000.0) ;
  $request = drupal_http_request($url ,$options) ;
  $data = drupal_json_decode($request->data) ;
  
  $liste_sinistres = array();
  foreach ($data as $contrat) {
    # code...
    $liste_sinistres[$contrat['numContrat']][] = $contrat;
  }

  
  /*$liste_sinistres = array (
   
      
    'CNTR00000031' => array (
      0 => array (
            'id' => 'SIN00000003',
            'numContrat' => 'CNTR00000031',
            'statut' =>  100000000,
            'typeEvent' =>  100000001,
            'typeSinistre' =>  'Automobile',
          ),
    ),

    'CNTR00000030' => array (
      0 => array (
            'id' => 'SIN00000004',
            'numContrat' => 'CNTR00000030',
            'statut' =>  100000000,
            'typeEvent' =>  100000002,
            'typeSinistre' =>  'Automobile',
          ),
      1 => array (
            'id' => 'SIN00000005',
            'numContrat' => 'CNTR00000030',
            'statut' =>  100000000,
            'typeEvent' =>  100000002,
            'typeSinistre' =>  'Automobile',
          ),
    ),

    'CNTR00000018' => array (
      0 =>array (
            'id' => 'SIN00000006',
            'numContrat' => 'CNTR00000018',
            'statut' => 100000001,
            'typeEvent' => 100000002,
            'typeSinistre' => 'Habitation',
          ),

      1 => array (
            'id' => 'SIN00000007',
            'numContrat' => 'CNTR00000018',
            'statut' => 100000001,
            'typeEvent' =>  100000001,
            'typeSinistre' => 'Habitation',
          ),
    ),

    'CNTR00000010' => array (
      0 =>array (
            'id' => 'SIN00000008',
            'numContrat' => 'CNTR00000010',
            'statut' => 100000002,
            'typeEvent' => 100000002,
            'typeSinistre' => 'Accident',
          ),

      1 => array (
            'id' => 'SIN00000009',
            'numContrat' => 'CNTR00000010',
            'statut' => 100000002,
            'typeEvent' =>  100000001,
            'typeSinistre' => 'Accident',
          ),
    ),
    'CNTR00000016' => array (
      0 =>array (
            'id' => 'SIN00000001',
            'numContrat' => 'CNTR00000016',
            'statut' => 100000001,
            'typeEvent' => 100000002,
            'typeSinistre' => 'Habitation',
          ),

      1 => array (
            'id' => 'SIN00000002',
            'numContrat' => 'CNTR00000016',
            'statut' => 100000001,
            'typeEvent' =>  100000001,
            'typeSinistre' => 'Habitation',
          ),
    ),


  );*/

  $tableau['thead'] = array(
    'date_survenance' => 'Date survenance',
    'numero_sinistre' => 'N° Sinistre',
    'evenements' => t('Evénements'),
    'status' => t('Status'),
  );

  $i=0;
  foreach ($liste_sinistres as $keys => $values) {
    # code...
    $Array_tmp1[$i]['type'] = $values[0]['typeSinistre'];
    $Array_tmp1[$i]['liste']['id']['numero_contrat'] = $values[0]['numContrat'];
    $Array_tmp1[$i]['liste']['id']['info_sup'] = 'a Faire';
    
    $k=0; 
    foreach ($values as $tab_body) {
      # code...
      $tableau['tbody'][$k]['date_survenance'] = '29/08/2017';  
      $tableau['tbody'][$k]['numero_sinistre'] = $tab_body['id'];
    
      if ($Array_tmp1[$i]['type'] === 'Habitation') {
        # code...
        $tableau['tbody'][$k]['evenements'] = $evenement_habitation[$tab_body['typeEvent']];
      }

      if ($Array_tmp1[$i]['type'] === 'Automobile') {
        # code...
        $tableau['tbody'][$k]['evenements'] = $evenement_auto[$tab_body['typeEvent']];
      }

      if($Array_tmp1[$i]['type'] === 'Accident'){
        $tableau['tbody'][$k]['evenements'] = $tab_body['typeEvent'];
      }

      if($Array_tmp1[$i]['type'] === 'Loisir'){
        $tableau['tbody'][$k]['evenements'] = $tab_body['typeEvent'];
      }

      $tableau['tbody'][$k]['status'] = $status[$tab_body['statut']];
      $k=$k+1;
    }

    $Array_tmp1[$i]['liste']['tableau'] = $tableau;
    $tableau = array();

    $i = $i+1;
  }
  
  
  foreach ($Array_tmp1 as $array) {
    # code...
    $Array_tmp2[$array['type']][] = $array['liste'];
      
  }

  $j=0;
  foreach ($Array_tmp2 as $key_tmp2 => $value_tmp2) {
    # code...
    $returnArray[$j]['type'] = $key_tmp2;
    $returnArray[$j]['liste'] = $value_tmp2;
    $j = $j+1;
  }
  
  //krumong('main')->kPrint($returnArray);die();

  return $returnArray;
}

function ws_client_get_liste_contrats(){
  // URL Webservice
  $ip = variable_get('ip_server');
  $root = variable_get('root');
  $liste_contrats = variable_get('retrieve_liste_contrats');


  $returnArray = array();

  $logement = array(
    0 => 'Bintou corrige',
    100000000 => 'Appartement',
    100000001 => 'Maison',
    100000002 => 'Autres',
  );

  $accident_tab = array(
    0 => 'Bintou corrige',
    100000000 => 'Voyage',
    100000001 => 'Evacuation Sanitaire',
    100000002 => 'Individuels accidents particulier',
  );

  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;


  /*$identifiant = 'AXA00000000';*/


  //$url = "http://192.168.200.16/Service1.svc/listeContrats/" .$identifiant. "";


 $url = 'http://'. $ip .'/'. $root .'/' . $liste_contrats .'/'. $identifiant;
  

  $options = array('timeout' => 6000.0) ;
  $request = drupal_http_request($url ,$options) ;
  $data = drupal_json_decode($request->data) ;
  
  foreach ($data as $assurance) {
    # code...
    if ($assurance['typeContrat'] == 'Habitation') {
      # code...
      $habitation['type'] = 'Habitation';
      $habitation['info'][] = array(
        'id' => $assurance['id'],
        'type_logement' => $logement[$assurance['typeLogement']],
        'adresse' => $assurance['adresseLogement'],  
      );

    }

    if ($assurance['typeContrat'] == 'Automobile') {
      # code...
      $auto['type'] = 'Auto';
      $auto['info'][] = array(
        'id' => $assurance['id'],
        'marque' => $assurance['marque'],
        'modele' => $assurance['modele'],  
      );
    }

    if ($assurance['typeContrat'] == 'Assistance & Accidents') {
      # code...
      $accident['type'] = 'Accident';
      $accident['info'][] = array(
        'id' => $assurance['id'],
        'produit' => $accident_tab[$assurance['typeAssurance']],
        'complete' => 'complete',  
      );  
    }

  }
  if (isset($auto)) {
    # code...
    $returnArray[] = $auto;
  }

  if (isset($habitation)) {
    # code...
    $returnArray[] = $habitation;
  }
  if (isset($accident)) {
    # code...
    $returnArray[] = $accident;
  }

  //var_dump($returnArray); die();
  
  return $returnArray;
}

function ws_client_get_liste_echeances(){
  // URL Webservice
  $ip = variable_get('ip_server');
  $root = variable_get('root');
  $liste_contrats = variable_get('retrieve_liste_contrats');


  $returnArray = array();

  $logement = array(
    0 => 'Bintou corrige',
    100000000 => 'Appartement',
    100000001 => 'Maison',
    100000002 => 'Autres',
  );

  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;

  $url = 'http://'. $ip .'/'. $root .'/' . $liste_contrats .'/'. $identifiant;

  $options = array('timeout' => 6000.0) ;
  $request = drupal_http_request($url ,$options) ;
  $data = drupal_json_decode($request->data) ;
  
  //var_dump($data); die();
  
  $table['thead'] = array(
      'NumContrat' => t('N° Contrat'),
      'caracteristiques' => t('Caractéristiques'),
      'mode_echeance' => t('Mode d\'echeance'),
      'prochaine_echeance' => t('Prochaine échéance'),
    );
    
    $i=0;
    //var_dump($data);
    foreach ($data as $echeance) {
      # code...
      $table['tbody'][$i]['NumContrat'] = $echeance['id'];
      if ($echeance['typeContrat'] == 'Habitation') {
        # code...
      $table['tbody'][$i]['caracteristiques'] = $echeance['adresseLogement'];
      }
      if ($echeance['typeContrat'] == 'Automobile') {
        # code...
      $table['tbody'][$i]['caracteristiques'] = $echeance['modele'];
      }
      if ($echeance['typeContrat'] == 'Accident') {
        # code...
      $table['tbody'][$i]['caracteristiques'] = 'aaa';
      }
      if ($echeance['typeContrat'] == 'Loisir') {
        # code...
      $table['tbody'][$i]['caracteristiques'] = 'bbb';
      }
      $table['tbody'][$i]['mode_echeance'] = t('Annuelle');
      $table['tbody'][$i]['prochaine_echeance'] = $echeance['echeance']; 
      
      $i=$i+1;
    }

  //var_dump($table);
  
  return $table;
}


function ws_client_get_liste_devis(){
  // URL Webservice
  $ip = variable_get('ip_server');
  $root = variable_get('root');
  $liste_devis = variable_get('retrieve_liste_devis');

  $returnArray = array();

  $type_habitation = array(
    'adresseLogement' => 'Adresse du logement',
    'id' => 'Numéro devis',
    'typeLogement' => 'Type de logement',
    'typeContrat' => 'Type contrat',
  );

  $type_auto = array(
    'marque' => 'Marque',
    'id' => 'Numéro devis',
    'modele' => 'Modèle',
    'typeContrat' => 'Type de contrat',
  );

  $type_accident = array(
    'typeAssurance' => "Type d'assurance",
    'id' => 'Numéro devis',
    'typeContrat' => 'Type contrat',
  );

 $type_loisir = array(
    'typeAssurance' => "Type d'assurance",
    'id' => 'Numéro devis',
    'typeContrat' => 'Type de contrat',
  );

  $logement = array(
    0 => 'Bintou corrige',
    100000000 => 'Appartement',
    100000001 => 'Maison',
    100000002 => 'Autres',
  );

  $accident_tab = array(
    0 => 'Bintou corrige',
    100000000 => 'Voyage',
    100000001 => 'Evacuation Sanitaire',
    100000002 => 'Individuels accidents particulier',
  );

   $loisir_tab = array(
    0 => 'Bintou corrige',
    100000000 => 'Plaisance',
    100000001 => 'RC chasse',
    100000002 => 'RC chevaux de selle',
    100000003 => 'RC chef de famille',
  );

  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;
  
  $url = 'http://'. $ip .'/'. $root .'/' . $liste_devis .'/'. $identifiant;

  //$url = "http://192.168.200.16/Service1.svc/listeDevis/" .$identifiant. "";

  $options = array('timeout' => 6000.0) ;
  $request = drupal_http_request($url ,$options) ;
  $data = drupal_json_decode($request->data) ;
if(isset($data)){

  foreach ($data as $assurance) {
    # code...
    if ($assurance['typeContrat'] == 'Habitation') {
      # code...
      $habitation['type'] = 'Type habitation';
      $i = 0;
      foreach ($assurance as $key => $value) {
        # code...
        if($value == TRUE && $key != 'typeContrat'){
          
          if ($key == 'typeLogement') {
            # code...
            $value = $logement[$value];
          }

          $habitation['tableau'][$i] = array(
              $type_habitation[$key],
              $value,
          );
        }
      $i = $i + 1;   
      }
    $returnArray[] = $habitation;
    }

    if ($assurance['typeContrat'] == 'Automobile') {
      # code...
      $auto['type'] = 'Type Auto';
      $i = 0;
      foreach ($assurance as $key => $value) {
        # code...
        if($value == TRUE && $key != 'typeContrat'){
          $auto['tableau'][$i] = array(
            $type_auto[$key],
            $value,
          );
        }
      $i = $i + 1; 
      }
    $returnArray[] = $auto;
    }

    if ($assurance['typeContrat'] == 'Assistance & Accidents') {
      # code...
      $accident['type'] = 'Type Assistance & Accidents';
      $i=0;
      foreach ($assurance as $key => $value) {
        # code...
        if($value == TRUE && $key != 'typeContrat'){
           if ($key == 'typeAssurance') {
            # code...
            $value = $accident_tab[$value];
          }
          $accident['tableau'][$i] = array(
            $type_accident[$key],
            $value,
          );
        }
      $i = $i + 1; 
      }
    $returnArray[] = $accident;
    }

    if ($assurance['typeContrat'] == 'Loisirs-Vie privée') {
      # code...
      $loisir['type'] = 'Loisirs-Vie privée';
      $i=0;
      foreach ($assurance as $key => $value) {
        # code...
        if($value == TRUE && $key != 'typeContrat'){
          if ($key == 'typeAssurance') {
            # code...
            $value = $loisir_tab[$value];
          }
          $loisir['tableau'][$i] = array(
            $type_loisir[$key],
            $value,
          );
        }
      $i = $i + 1; 
      }
    $returnArray[] = $loisir;
    }

  }
    
  return $returnArray;
}





function ws_client_get_echeance(){
  $ip = variable_get('ip_server');
  $root = variable_get('root');
  $liste_echeances = variable_get('retrieve_liste_echeances');
  $returnArray = array();
  
  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;

  $url = 'http://'. $ip .'/'. $root .'/' . $liste_echeances .'/'. $identifiant;

  //$url = "http://192.168.200.16/Service1.svc/listeEcheances/" .$identifiant. "";

  $options = array('timeout' => 6000.0) ;
  $request = drupal_http_request($url ,$options) ;
  $data = drupal_json_decode($request->data) ;

  $returnArray['thead'] = array(
    'NumContrat' => t('N° Contrat'),
    'produit' => t('Produit'),
    'caracteristiques' => t('Caractéristiques'),
    'mode_echeance' => t('Mode d\'echeance'),
    'prochaine_echeance' => t('Prochaine échéance'),
  );

  foreach ($data as $echeance) {
    $returnArray['tbody'][] = array(
      'NumContrat' => $echeance['numContrat'],
      'produit' => $echeance['produit'],
      'caracteristiques' => $echeance['caracteristiques'],
      'mode_echeance' => $echeance['modeEcheance'],
      'prochaine_echeance' => $echeance['prochaineEcheance'],
    );
  }
   } 
  return $returnArray;
}


function ws_client_get_info_conseiller(){
  //URL WEBSERVICE
  $ip = variable_get('ip_server');
  $root = variable_get('root');
  $info_conseiller = variable_get('retrieve_conseiller');

  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;

  //$url = "http://192.168.200.16/Service1.svc/conseiller/" .$identifiant. "";

  $url = 'http://'. $ip .'/'. $root .'/' . $info_conseiller .'/'. $identifiant;

  $options = array('timeout' => 6000.0) ;
  $request = drupal_http_request($url ,$options) ;
  $data = drupal_json_decode($request->data) ;
   
  $returnArray = array(
    'nomComplet' => $data['nomComplet'] ,
    'adresse' => $data['adresse'] ,
    'telephone' => $data['telephone'] ,
    'mail' => $data['mail'],
    //'img' => $data['imageUrl'],
    'agence' => $data['agence'], 
  );

  return $returnArray ;
}

function ws_client_declarer_sinistre($data){
  $ip = variable_get('ip_server');
  $root = variable_get('root');
  $declarer_sinistre = variable_get('declarer_sinistre');

  $url = 'http://'. $ip .'/'. $root .'/' . $declarer_sinistre;

  $data = drupal_json_encode($data);

  $options = array(
    'method' => 'POST',
    'data' => $data,
    'timeout' => 6000.0,
    'headers' => array('Content-Type' => 'application/json'),
  );

 /* $result = drupal_http_request('http://192.168.43.145/Service1.svc/sinistre/create', $options);*/

  $result = drupal_http_request($url, $options);

}

function ws_client_update_info_user($array_data) {
  $ip = variable_get('ip_server');
  $root = variable_get('root');
  $update_info_user = variable_get('update_info_user');

  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;

  $array_data['id'] = $identifiant;
  $data = drupal_json_encode($array_data);

  $options = array(
                  'method' => 'PUT',
                  'data' => $data,
                  'timeout' => 6000.0,
                  'headers' => array('Content-Type' => 'application/json')
  );

  //$url = 'http://192.168.200.16/Service1.svc/compte/update';

  $url = 'http://'. $ip .'/'. $root .'/' . $update_info_user;

  $result = drupal_http_request($url, $options);
          
}

function ws_client_user_login(&$edit, $account) {
 // URL Webservice
  $ip = variable_get('ip_server');
  $root = variable_get('root');
  $info_user = variable_get('retrieve_info_user');

  global $user;

  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;
  //$url = "http://192.168.200.16/Service1.svc/compte/espaceClient/infos/" .$identifiant. "";

  $url = 'http://'. $ip .'/'. $root .'/' . $info_user .'/'. $identifiant;
  $options = array('timeout' => 500.0) ;
  $request = drupal_http_request($url ,$options) ;
  
  $data = drupal_json_decode($request->data) ;

  variable_set('nom_'.$user->uid, $data['nom']);
  variable_set('prenom_'.$user->uid, $data['prenom']);
  variable_set('adresse_'.$user->uid, $data['adresse']);
  variable_set('telephone_'.$user->uid, $data['telephone']);
  variable_set('mail_'.$user->uid, $data['mail']);
}


function ws_client_user_logout($account) {
global $user;

  $nom = variable_get('nom_'.$user->uid);
  $prenom = variable_get('prenom_'.$user->uid);
  $adresse = variable_get('adresse_'.$user->uid);
  $tel = variable_get('telephone_'.$user->uid);
  $email= variable_get('mail_'.$user->uid);

 if(!isset($nom) && !isset($prenom) && !isset($adresse) && !isset($tel) && !isset($email)){
    variable_del('nom_'.$user->uid);
    variable_del('prenom_'.$user->uid);
    variable_del('adresse_'.$user->uid);
    variable_del('telephone_'.$user->uid);
    variable_del('mail_'.$user->uid);

   /* variable_del('nom');
    variable_del('prenom');
    variable_del('adresse');
    variable_del('telephone');
    variable_del('mail');*/
  }

}

function ws_client_user_presave(&$edit, $account, $category) {
  // URL WEBSERVICE  

  if(isset( $edit['field_numero_contrat']['und'][0]['value']))
  {
  	$numContrat = $edit['field_numero_contrat']['und'][0]['value']	 ;
  	$identifiantClient = ws_client_getIdClient($numContrat);
    if(!empty($identifiantClient) )	
    $edit['field_identifiant_client']['und'][0]['value'] = $identifiantClient ;
  }
    /*var_dump($result) ;  die();*/
 /* if($result != 'false')*/
}

function ws_client_webform_component_render_alter(&$element, &$component) {
   global $user;
   //krumong('main')->kPrint($element) ;
   //$element['#readonly'] = 'true';
   if (in_array('client', array_values($user->roles))) {
     // $infoUser = ws_client_getInfoUser() ;
    // var_dump($infoUser) ; die();
   
    /*  $nom = $infoUser['nom'];
      $prenom = $infoUser['prenom'];
      
      $email = $infoUser['mail'];
      $tel = $infoUser['telephone'];*/


   if (in_array('client', array_values($user->roles))) {

    $nom = variable_get('nom_'.$user->uid);
    $prenom = variable_get('prenom_'.$user->uid);      
    $email = variable_get('mail_'.$user->uid);
    $adresse = variable_get('adresse_'.$user->uid);    
    $tel = variable_get('telephone_'.$user->uid);

    $title =$element['#title'];

      switch ($title) {
        case 'Nom':
        case 'Nom ':
        case 'nom ':
        case 'nom':
          $element['#default_value'] =  $nom;
          $element['#attributes']= array('disabled' => '1');
          break;
        case 'Prènom':
        case 'Prenom':
        case 'Prénom':
          $element['#default_value'] = $prenom;
           $element['#attributes']= array('disabled' => '1');
          break;
         case 'Email':
          $element['#default_value'] = $email;
          $element['#attributes']= array('disabled' => '1');
          break;
        case 'Téléphone':
          $element['#default_value'] = $tel;
           $element['#attributes']= array('disabled' => '1');
          break;
        
        default:

          break;
      }
    }

}


function ws_client_webform_submission_presave($node, &$submission) {
  //var_dump($submission) ;die();

    global $user;
    $identifiant = "" ;
    $uid = ($user->uid); 
    $nid = $node->nid ;
   if($uid != 0)
    {
      $account = user_load($user->uid);
      $identifiant = $account->field_identifiant_client['und'][0]['value'] ;
    }
    $result = ws_client_createDevis($nid , $submission , $identifiant) ;
   //  var_dump($result) ; die();
    if($result->code >=  300 )
    {
     drupal_set_message(t("Le devis n'a pas ete créé veuillez verifier les données saisies"  ,'error'));
      switch ($nid) {
        case 8:
           drupal_goto("node/8");
          break;
          case 9:
           drupal_goto("node/9");
          break;
          case 10:
           drupal_goto("node/10");
          break;
          case 11:
           drupal_goto("node/11");
          break;
        
        default:
          # code...
          break;
      }
    }
    /* var_dump($identifiant) ;die() ;*/
      
           webform_submission_delete($node, $submission);
}

function ws_client_createDevis($idNode, $submission ,$identifiant){
  $ip = variable_get('ip_server');
  $root = variable_get('root');
  $create_devis_auto = variable_get('create_devis_auto');
  $create_devis_habitation = variable_get('create_devis_habitation');
  $create_devis_accident = variable_get('create_devis_accident');
  $create_devis_loisir = variable_get('create_devis_loisir');
  $result = "" ;
  if($idNode == 8)
      {
            $carrosserieObject = taxonomy_term_load($submission->data[12][0]) ;
            $carroserie = $carrosserieObject->name ;
            $idCarroserie = $carrosserieObject->tid ;
            $modeleVehiculeObjectParent = taxonomy_get_parents($idCarroserie) ;
            $modeleVehiculeObject = reset($modeleVehiculeObjectParent) ;
            $modeleVehicule = $modeleVehiculeObject->name ;
            $idmodel = $modeleVehiculeObject->tid ;
            $marqueObjectParent = (taxonomy_get_parents($idmodel)) ;
            $marqueObject  = reset($marqueObjectParent) ;
            $marque = $marqueObject->name ;
            $devis = array(
             'idCompte' =>$identifiant ,
             'nom' => $submission->data[1][0] ,
             'prenom' => $submission->data[2][0] , 
            /* 'dateNaissance' => $submission->data[3][0] ,*/ 
             'telephone' => $submission->data[21][0]  ,
             'mail' => $submission->data[4][0] ,
            /* 'dateMiseCirculation' => $submission->data[19][0] ,*/
             /*'ageObtentionPermis' => $submission->data[16][0] ,*/
             'carburant' => $submission->data[13][0] ,
             'valeurAneuf' => $submission->data[20][0] ,
          /*   'emailDuconducteurPrincipal' => $submission->data[17][0] ,*/
             'marque' =>  $marque ,
             'carosserie' => $carroserie ,
             'modele' => $modeleVehicule,
             'puissane' => $submission->data[18][0]
             /*'adresse' => $submission->data[21][0] */
             /*'anneeDeNaissanceconducteur' => $submission->data[15][0] */
             );
            
            $data = drupal_json_encode($devis);

              $options = array(
                              'method' => 'POST',
                              'data' => $data,
                              'timeout' => 6000.0,
                              'headers' => array('Content-Type' => 'application/json')
              );

              //$result = drupal_http_request("http://192.168.200.16/Service1.svc/devisAuto/create", $options);

              $url = 'http://'. $ip .'/'. $root .'/' . $create_devis_auto;

              $result = drupal_http_request($url, $options);
              
        }
         if($idNode == 9)
          { 
            $devis = array(
             'idCompte' => $identifiant ,
             'nom' => $submission->data[8][0],
             'prenom' => $submission->data[9][0], 
             'telephone' => $submission->data[11][0],
             'mail' => $submission->data[12][0],
             'typeLogement' => $submission->data[14][0],
             'adresseLogement' => $submission->data[4][0],
             'nbPieces' =>  $submission->data[2][0],
             'principal' => $submission->data[3][0],
             'locataire' => $submission->data[15][0],
             'montant' => '5000000'
             );
            $data = drupal_json_encode($devis);

              $options = array(
                              'method' => 'POST',
                              'data' => $data,
                              'timeout' => 6000.0,
                              'headers' => array('Content-Type' => 'application/json')
              );

              $url = 'http://'. $ip .'/'. $root .'/' . $create_devis_habitation;

              $result = drupal_http_request($url, $options);

           }

          if($idNode == 10)
          { 
            $devis = array(
              "idCompte" => $identifiant,
              "nom" => $submission->data[1][0],
              "prenom" => $submission->data[2][0],
              "telephone" => $submission->data[4][0],
              "mail" => $submission->data[5][0],
              "typeAssurance" => $submission->data[9][0] 
             );
              /*var_dump($devis); die();*/
            $data = drupal_json_encode($devis);

              $options = array(
                              'method' => 'POST',
                              'data' => $data,
                              'timeout' => 6000.0,
                              'headers' => array('Content-Type' => 'application/json')
              );


              //$result = drupal_http_request("http://192.168.43.145/Service1.svc/devisAssistanceAccident/create", $options);


            $url = 'http://'. $ip .'/'. $root .'/' . $create_devis_accident;
            $result = drupal_http_request($url, $options);
              /*var_dump( $result) ; die();*/
          }
          if($idNode == 11)
          { 
            $devis = array(
             'idCompte' => $identifiant ,
             /*'civilite' => $submission->data[1][0],*/
             'nom' => $submission->data[2][0],
             'prenom' => $submission->data[3][0],
             /* 'dateNaissance' => $submission->data[4][0] ,*/  
             'mail' => $submission->data[5][0],
             'telephone' => $submission->data[6][0],
             'typeAssurance' => $submission->data[7][0]
             );
              /*var_dump($devis); die();*/
            $data = drupal_json_encode($devis);

              $options = array(
                              'method' => 'POST',
                              'data' => $data,
                              'timeout' => 6000.0,
                              'headers' => array('Content-Type' => 'application/json')
              );

           // $result = drupal_http_request("http://192.168.43.145/Service1.svc/devisLoisirs/create", $options);

            $url = 'http://'. $ip .'/'. $root .'/' . $create_devis_loisir;
            $result = drupal_http_request($url, $options);
             /* var_dump( $result) ; die();*/
          }
          return $result ;
}




