<?php

/**
 * @file
 * ws_client module
 */

/**
 * Define constants for ws_client
 */
define('WS_CLIENT_ADMIN_PATH', 'admin/config/system/ws_client');



/**
 * Load module include files.
 */
module_load_include('inc', 'ws_client', 'ws_client.admin');

/**
 * Implements hook_permission()
 */
function ws_client_permission() {
  return array(
    'administer  ws_client' => array(
    'title' => t('administer ws client'),
    'description' => t('Perform administration end point ws client.'),
    ),
  );
}

/**
 * Implements hook_menu()
 */
function ws_client_menu() {
  $items[WS_CLIENT_ADMIN_PATH] = array(
    'title' => 'WS Client Settings',
    'description' => 'Administer your ws clien',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ws_client_admin_form'),
    'access arguments' => array('administer ws_client'),
    'file' => 'ws_client.admin.inc',
  );

  return $items;
}

	/**
	* @file
	* Web services Client
	*/
function  ws_client_block_info() {
	$blocks['ws_client_block_info'] = array('info' => t('web service client'));
	return $blocks ;
}
function  ws_client_block_view($delta = '') {
	$block['content'] = '<h1>Web Services client</h1>';
	$get_node_result = ws_client_getClient_node();
	/*krumong('main')->kPrint($get_node_result);*/	
	$data = json_decode($get_node_result->data);
	/*krumong('main')->kPrint($data);*/
	return $block ;
}

function ws_client_get_node(){
	$url = "http://192.168.1.1021.10243.145/ServicesCompte.svc/compte/espaceClient/AXA00000004/" ;
  $options = array('timeout' => 6000.0) ;
	return drupal_http_request($url , $options) ;
}


function ws_client_getIdClient($numeroContrat){
	$url = "http://192.168.43.145/Service1.svc/compte/espaceClient/id/". $numeroContrat ."";

  $options = array('timeout' => 6000.0) ;
	$request = drupal_http_request($url ,$options) ;
  /*var_dump($request->data);die();*/
  return drupal_json_decode($request->data);
}

function ws_client_getInfoUser(){
  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;
  /*var_dump($identifiant) ; die();*/
  $url = "http://192.168.43.145/Service1.svc/compte/espaceClient/infos/" .$identifiant. "";
  $options = array('timeout' => 6000.0) ;
  $request = drupal_http_request($url ,$options) ;
  $data = drupal_json_decode($request->data) ;
  
  $returnArray = array(
    'nom' => $data['nom'] ,
    'prenom' => $data['prenom'] ,
    'adresse' => $data['adresse'] ,
    'telephone' => $data['telephone'] ,
    'mail' => $data['mail'], 
  );

  return $returnArray ;
}

function ws_client_get_liste_contrats(){
  $returnArray = array();
  $habitation = array();
  $auto = array();
  $accident = array();
  $loisir = array();

  $logement = array(
    0 => 'Bintou corrige',
    100000000 => 'Appartement',
    100000001 => 'Maison',
    100000002 => 'Autres',
  );

  $accident_tab = array(
    0 => 'Bintou corrige',
    100000000 => 'Voyage',
    100000001 => 'Evacuation Sanitaire',
    100000002 => 'Individuels accidents particulier',
  );

  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;

  /*$identifiant = 'AXA00000000';*/


  $url = "http://192.168.43.145/Service1.svc/listeContrats/" .$identifiant. "";
  $options = array('timeout' => 6000.0) ;
  $request = drupal_http_request($url ,$options) ;
  $data = drupal_json_decode($request->data) ;
  
  foreach ($data as $assurance) {
    # code...
    if ($assurance['typeContrat'] == 'Habitation') {
      # code...
      $habitation['type'] = 'Habitation';
      $habitation['info'][] = array(
        'id' => $assurance['id'],
        'type_logement' => $logement[$assurance['typeLogement']],
        'adresse' => $assurance['adresseLogement'],  
      );

    }

    if ($assurance['typeContrat'] == 'Automobile') {
      # code...
      $auto['type'] = 'Auto';
      $auto['info'][] = array(
        'id' => $assurance['id'],
        'marque' => $assurance['marque'],
        'modele' => $assurance['modele'],  
      );
    }

    if ($assurance['typeContrat'] == 'Assistance & Accidents') {
      # code...
      $accident['type'] = 'Accident';
      $accident['info'][] = array(
        'id' => $assurance['id'],
        'produit' => $accident_tab[$assurance['typeAssurance']],
        'complete' => 'complete',  
      );  
    }

  }
  
  $returnArray[] = $auto;
  $returnArray[] = $habitation;
  $returnArray[] = $accident;
  
  return $returnArray;
}

function ws_client_get_liste_devis(){
  $returnArray = array();
  $habitation = array();
  $auto = array();
  $accident = array();
  $loisir = array();

  $type_habitation = array(
    'adresseLogement' => 'Adresse du logement',
    'id' => 'Numéro devis',
    'typeLogement' => 'Type de logement',
    'typeContrat' => 'Type contrat',
  );

  $type_auto = array(
    'marque' => 'Marque',
    'id' => 'Numéro devis',
    'modele' => 'Modèle',
    'typeContrat' => 'Type de contrat',
  );

  $type_accident = array(
    'typeAssurance' => "Type d'assurance",
    'id' => 'Numéro devis',
    'typeContrat' => 'Type contrat',
  );

 $type_loisir = array(
    'typeAssurance' => "Type d'assurance",
    'id' => 'Numéro devis',
    'typeContrat' => 'Type de contrat',
  );

  $logement = array(
    0 => 'Bintou corrige',
    100000000 => 'Appartement',
    100000001 => 'Maison',
    100000002 => 'Autres',
  );

  $accident_tab = array(
    0 => 'Bintou corrige',
    100000000 => 'Voyage',
    100000001 => 'Evacuation Sanitaire',
    100000002 => 'Individuels accidents particulier',
  );

   $loisir_tab = array(
    0 => 'Bintou corrige',
    100000000 => 'Plaisance',
    100000001 => 'RC chasse',
    100000002 => 'RC chevaux de selle',
    100000003 => 'RC chef de famille',
  );

  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;

 /* $identifiant = 'AXA00000000';*/


  $url = "http://192.168.43.145/Service1.svc/listeDevis/" .$identifiant. "";
  $options = array('timeout' => 6000.0) ;
  $request = drupal_http_request($url ,$options) ;
  $data = drupal_json_decode($request->data) ;
if(isset($data)){

  foreach ($data as $assurance) {
    # code...
    if ($assurance['typeContrat'] == 'Habitation') {
      # code...
      $habitation['type'] = 'Type habitation';
      $i = 0;
      foreach ($assurance as $key => $value) {
        # code...
        if($value == TRUE && $key != 'typeContrat'){
          
          if ($key == 'typeLogement') {
            # code...
            $value = $logement[$value];
          }

          $habitation['tableau'][$i] = array(
              $type_habitation[$key],
              $value,
          );
        }
      $i = $i + 1;   
      }
    $returnArray[] = $habitation;
    }

    if ($assurance['typeContrat'] == 'Automobile') {
      # code...
      $auto['type'] = 'Type Auto';
      $i = 0;
      foreach ($assurance as $key => $value) {
        # code...
        if($value == TRUE && $key != 'typeContrat'){
          $auto['tableau'][$i] = array(
            $type_auto[$key],
            $value,
          );
        }
      $i = $i + 1; 
      }
    $returnArray[] = $auto;
    }

    if ($assurance['typeContrat'] == 'Assistance & Accidents') {
      # code...
      $accident['type'] = 'Type Assistance & Accidents';
      $i=0;
      foreach ($assurance as $key => $value) {
        # code...
        if($value == TRUE && $key != 'typeContrat'){
           if ($key == 'typeAssurance') {
            # code...
            $value = $accident_tab[$value];
          }
          $accident['tableau'][$i] = array(
            $type_accident[$key],
            $value,
          );
        }
      $i = $i + 1; 
      }
    $returnArray[] = $accident;
    }

    if ($assurance['typeContrat'] == 'Loisirs-Vie privée') {
      # code...
      $loisir['type'] = 'Loisirs-Vie privée';
      $i=0;
      foreach ($assurance as $key => $value) {
        # code...
        if($value == TRUE && $key != 'typeContrat'){
          if ($key == 'typeAssurance') {
            # code...
            $value = $loisir_tab[$value];
          }
          $loisir['tableau'][$i] = array(
            $type_loisir[$key],
            $value,
          );
        }
      $i = $i + 1; 
      }
    $returnArray[] = $loisir;
    }

  }
    
  return $returnArray;
}

function ws_client_get_echeance(){
  $returnArray = array();
  
  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;

  //$identifiant = 'AXA00000000';

  $url = "http://192.168.43.145/Service1.svc/listeEcheances/" .$identifiant. "";
  $options = array('timeout' => 6000.0) ;
  $request = drupal_http_request($url ,$options) ;
  $data = drupal_json_decode($request->data) ;

  $returnArray['thead'] = array(
    'NumContrat' => t('N° Contrat'),
    'produit' => t('Produit'),
    'caracteristiques' => t('Caractéristiques'),
    'mode_echeance' => t('Mode d\'echeance'),
    'prochaine_echeance' => t('Prochaine échéance'),
  );

  foreach ($data as $echeance) {
    $returnArray['tbody'][] = array(
      'NumContrat' => $echeance['numContrat'],
      'produit' => $echeance['produit'],
      'caracteristiques' => $echeance['caracteristiques'],
      'mode_echeance' => $echeance['modeEcheance'],
      'prochaine_echeance' => $echeance['prochaineEcheance'],
    );
  }
   } 
  return $returnArray;
}


function ws_client_get_info_conseiller(){
  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;
 
  $url = "http://192.168.43.145/Service1.svc/conseiller/" .$identifiant. "";
  $options = array('timeout' => 6000.0) ;
  $request = drupal_http_request($url ,$options) ;
  $data = drupal_json_decode($request->data) ;
   
  $returnArray = array(
    'nomComplet' => $data['nomComplet'] ,
    'adresse' => $data['adresse'] ,
    'telephone' => $data['telephone'] ,
    'mail' => $data['mail'], 
  );
   
  return $returnArray ;
}

function ws_client_declarer_sinistre($data){
  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;

  $data['id'] = $identifiant;
  $data = drupal_json_encode($data);

  $options = array(
    'method' => 'POST',
    'data' => $data,
    'timeout' => 6000.0,
    'headers' => array('Content-Type' => 'application/json'),
  );

  $result = drupal_http_request('http://192.168.43.145/Service1.svc/sinistre/create', $options);
}

function ws_client_update_info_user($array_data) {
  global $user;
  $account = user_load($user->uid);
  $identifiant = $account->field_identifiant_client['und'][0]['value'] ;

  $array_data['id'] = $identifiant;
  $data = drupal_json_encode($array_data);

  $options = array(
                  'method' => 'PUT',
                  'data' => $data,
                  'timeout' => 6000.0,
                  'headers' => array('Content-Type' => 'application/json')
  );

  $url = 'http://192.168.43.145/Service1.svc/compte/update';

  $result = drupal_http_request($url, $options);
          
}




/*function ws_client_getIdentifiant_node(){

	$url = 'http://192.168.43.145/ServicesCompte.svc/compte/espaceClient/AXA00000004/' ;
	return drupal_http_request($url) ;
}*/
function ws_client_user_login(&$edit, $account) {
  $edit['redirect'] = 'node/123';
}

function ws_client_user_presave(&$edit, $account, $category) {
  if(isset( $edit['field_numero_contrat']['und'][0]['value']))
  {
  	$numContrat = $edit['field_numero_contrat']['und'][0]['value']	 ;
  	$result = ws_client_getIdClient($numContrat);	
    $edit['field_identifiant_client']['und'][0]['value'] = $result ;
  }
    /*var_dump($result) ;  die();*/
 /* if($result != 'false')*/
}
function ws_client_webform_submission_presave($node, &$submission) {
  //var_dump($submission) ;die();

    global $user;
    $identifiant = "" ;
    $uid = ($user->uid); 
    $nid = $node->nid ;
   if($uid != 0)
    {
      $account = user_load($user->uid);
      $identifiant = $account->field_identifiant_client['und'][0]['value'] ;
    }
    /* var_dump($identifiant) ;die() ;*/
      if($nid == 8)
      {
            $carrosserieObject = taxonomy_term_load($submission->data[12][0]) ;
            $carroserie = $carrosserieObject->name ;
            $idCarroserie = $carrosserieObject->tid ;
            $modeleVehiculeObjectParent = taxonomy_get_parents($idCarroserie) ;
            $modeleVehiculeObject = reset($modeleVehiculeObjectParent) ;
            $modeleVehicule = $modeleVehiculeObject->name ;
            $idmodel = $modeleVehiculeObject->tid ;
            $marqueObjectParent = (taxonomy_get_parents($idmodel)) ;
            $marqueObject  = reset($marqueObjectParent) ;
            $marque = $marqueObject->name ;
            $devis = array(
             'idCompte' =>$identifiant ,
             'nom' => $submission->data[1][0] ,
             'prenom' => $submission->data[2][0] , 
            /* 'dateNaissance' => $submission->data[3][0] ,*/ 
             'telephone' => $submission->data[5][0]  ,
             'mail' => $submission->data[4][0] ,
            /* 'dateMiseCirculation' => $submission->data[19][0] ,*/
             /*'ageObtentionPermis' => $submission->data[16][0] ,*/
             'carburant' => $submission->data[13][0] ,
             'valeurAneuf' => $submission->data[20][0] ,
          /*   'emailDuconducteurPrincipal' => $submission->data[17][0] ,*/
             'marque' =>  $marque ,
             'carosserie' => $carroserie ,
             'modele' => $modeleVehicule,
             'puissane' => $submission->data[18][0]
             /*'adresse' => $submission->data[21][0] */
             /*'anneeDeNaissanceconducteur' => $submission->data[15][0] */
             );
             /* var_dump($devis); die();*/
            $data = drupal_json_encode($devis);

              $options = array(
                              'method' => 'POST',
                              'data' => $data,
                              'timeout' => 6000.0,
                              'headers' => array('Content-Type' => 'application/json')
              );

              $result = drupal_http_request("http://192.168.43.145/Service1.svc/devisAuto/create", $options);
        }
         if($nid == 9)
          { 
            $devis = array(
             'idCompte' => $identifiant ,
             'nom' => $submission->data[8][0],
             'prenom' => $submission->data[9][0], 
             'telephone' => $submission->data[11][0],
             'mail' => $submission->data[12][0],
             'typeLogement' => $submission->data[14][0],
             'adresseLogement' => $submission->data[4][0],
             'nbPieces' =>  $submission->data[2][0],
             'principal' => $submission->data[3][0],
             'locataire' => $submission->data[15][0],
             'montant' => '5000000'
             );
             /* var_dump($devis); die();*/
            $data = drupal_json_encode($devis);

              $options = array(
                              'method' => 'POST',
                              'data' => $data,
                              'timeout' => 6000.0,
                              'headers' => array('Content-Type' => 'application/json')
              );

              $result = drupal_http_request("http://192.168.43.145/Service1.svc/devisHabitation/create", $options);
              /*var_dump( $result) ; die();*/
          }
          if($nid == 10)
          { 
            $devis = array(
              "idCompte" => $identifiant,
              "nom" => $submission->data[1][0],
              "prenom" => $submission->data[2][0],
              "telephone" => $submission->data[4][0],
              "mail" => $submission->data[5][0],
              "typeAssurance" => $submission->data[9][0] 
             );
              /*var_dump($devis); die();*/
            $data = drupal_json_encode($devis);

              $options = array(
                              'method' => 'POST',
                              'data' => $data,
                              'timeout' => 6000.0,
                              'headers' => array('Content-Type' => 'application/json')
              );

              $result = drupal_http_request("http://192.168.43.145/Service1.svc/devisAssistanceAccident/create", $options);
              /*var_dump( $result) ; die();*/
          }
          if($nid == 11)
          { 
            $devis = array(
             'idCompte' => $identifiant ,
             /*'civilite' => $submission->data[1][0],*/
             'nom' => $submission->data[2][0],
             'prenom' => $submission->data[3][0],
             /* 'dateNaissance' => $submission->data[4][0] ,*/  
             'mail' => $submission->data[5][0],
             'telephone' => $submission->data[6][0],
             'typeAssurance' => $submission->data[7][0]
             );
              /*var_dump($devis); die();*/
            $data = drupal_json_encode($devis);

              $options = array(
                              'method' => 'POST',
                              'data' => $data,
                              'timeout' => 6000.0,
                              'headers' => array('Content-Type' => 'application/json')
              );

              $result = drupal_http_request("http://192.168.43.145/Service1.svc/devisLoisirs/create", $options);
             /* var_dump( $result) ; die();*/
          }
           webform_submission_delete($node, $submission);
}
