<?php
/**
 * Implements hook_block_info()
 */
function declarer_sinistre_block_info() {
  return array(
    'declarer_sinistre' => array(
      'info' => t('Declarer un sinistre'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view()
 */
function declarer_sinistre_block_view($delta = '') {
  $block = array();
  if ($delta == 'declarer_sinistre') {
    $block['subject'] = '<p>'. 'Declarer Sinistre' .'</p>'; 
    $block['content'] = drupal_get_form('fixer_declarer_sinistre_form');
  }

  return $block;
}

/**
 * fixer_declarer_sinistre_form
 */
function fixer_declarer_sinistre_form($form, &$form_state){

  
  
  return system_settings_form($form);

}