<?php
/**
 * Implements hook_block_info()
 */
function echeances_block_info() {
  return array(
    'echeances' => array(
      'info' => t('echeances client'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_block_view()
 */
function echeances_block_view($delta = '') {
  if ($delta == 'echeances') {
    $today = date("d/m/Y");
    
  	$title_echeance = t('Mes échéances');
  	$title_p = t('Situation au ' . $today); 
  	$title = '<p>'. $title_echeance .'</p>';
  	$title .= '<span>'. $title_p .'</span>';
  	$text_prime = t("Dates des prochaines primes à payer pour vos contrat d'assurance");
  	$text_contact = t('Pour toute information supplémentaire contacter votre conseiller');
  	$output = '';

  	$table = array(
	  	'thead' => array(
	  		'NumContrat' => t('N° Contrat'),
	  		'produit' => t('Produit'),
	  		'caracteristiques' => t('Caractéristiques'),
	  		'mode_echeance' => t('Mode d\'echeance'),
	  		'prochaine_echeance' => t('Prochaine échéance'),
	  	),
	  	'tbody' => array(
	  		array(
		  	  'NumContrat' => t('10245520'),
		  		'produit' => t('Oplus LIFE-Equatoria'),
		  		'caracteristiques' => t('BMW'),
		  		'mode_echeance' => t('Mensuelle'),
		  		'prochaine_echeance' => t('01/09/2017'),		
	  		),
	  		array(
		  	  'NumContrat' => t('1254885222'),
		  		'produit' => t('Oplus LIFE-Equatoria'),
		  		'caracteristiques' => t('BMW'),
		  		'mode_echeance' => t('Mensuelle'),
		  		'prochaine_echeance' => t('01/09/2017'),		
	  		),
	  		array(
		  	    'NumContrat' => t('125460'),
		  		'produit' => t('Oplus LIFE-Equatoria'),
		  		'caracteristiques' => t('BMW'),
		  		'mode_echeance' => t('Mensuelle'),
		  		'prochaine_echeance' => t('01/09/2017'),		
	  		),
	  	),
  	); 

    $output .= '<p>'. $text_prime .'</p>';
    $output .= '<table class="table-bordered">';
    $output .=   '<thead>';
    
    foreach ($table['thead'] as $key => $value) {
    	# code...
        $output .=     '<th>'. $value .'</th>';
    }

    $output .=   '</thead>';
    $output .=   '<tbody>';
    foreach ($table['tbody'] as $tables) {
    	# code...
    	$output .= '<tr>';
    	foreach ($tables as $key => $value) {
    		# code...
    		$output .=   '<td>'. $value .'</td>';
    	}
    	$output .= '</tr>';
    }
    $output .=   '</tbody>';
    $output .= '</table>';
    $output .= '<p>'. $text_contact .'</p>';
    return array(
      'subject' => $title,
      'content' => (!empty($output)) ? '<div class="echeance_body">' . $output . '</div>' : '<p>' . t('For now, this list is empty!') . '</p>',
    );
  }

  return array();
}